### ISSUE TITLE
Package broke with 

### ISSUE THREAD

**Issue by Enaah** [alajusticia/laravel-auth-tracker#2]
Hi there,

with the update of Version 1.5 of `alajusticia/laravel-expirable` (https://github.com/alajusticia/laravel-expirable/releases/tag/v1.5) this package is broken:

![Bildschirmfoto 2021-09-23 um 17 11 56](https://user-images.githubusercontent.com/10073766/134534297-23c410b1-60d8-41e6-a093-a6bb2ef4755e.jpg)

This is a heads up. I will try to do an PR.

Cheers

**Comment by Enaah** [comment]
Okay, i'm not quite getting how to migrate the package to the new `laravel-expirable` version.
I locked it at version `1.4`.
I think/hope it's easier for you.

**Comment by alajusticia** [comment]
Hi @Enaah, thanks for reporting this issue.

I released a fix, it should work now ;)
