### ISSUE TITLE
Error in getIsCurrentAttribute() when logins are requested via ajax calls

### ISSUE THREAD

**Issue by zhiyong-ft** [alajusticia/laravel-auth-tracker#3]
Hi,

Thanks for the package. I ran into some problem described below:
```
// routes/api.php
Route::group(['middleware' => 'auth:api'], function () {
    Route::get('logins', 'ApiController@getLogins');
});
```
```
// ApiController.php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ApiController extends Controller
{
    public function getLogins(Request $request)
    {
        return response()->json($request->user()->logins->sortByDesc('is_current'));
    }
}
```

Such setup works fine when logins API is queried by Postman, but when the same API is queried by AJAX calls via axios, I will have the following error:
```
"message": "Undefined property: Laravel\\Passport\\TransientToken::$id",
    "exception": "ErrorException",
    "file": "vendor\\alajusticia\\laravel-auth-tracker\\src\\Models\\Login.php",
    "line": 112,
```
My understanding is AJAX calls using session CSRF token confused getIsCurrentAttribute().

**Comment by zhiyong-ft** [comment]
I did some debugging. It seems when AJAX calls are authenticated by Passport via guard(auth:api):
```
request()->user()->token()
```
will be NULL, therefore calling 
```
request()->user()->token()->id 
```
will throw exception.

**Comment by alajusticia** [comment]
Hi, this package is now discontinued and replaced by a new one that supports Laravel 10 and 11: [Laravel Logins](https://github.com/alajusticia/laravel-logins)
