### ISSUE TITLE
Laravel 10 compatibility

### ISSUE THREAD

**Issue by JorgenSolli** [alajusticia/laravel-auth-tracker#6]
Hi there! Thank you for this package, great work!

Will this receive Laravel 10 support, or is this project abandoned?

**Comment by alajusticia** [comment]
Hi, the package is not abandoned, I was working on a v3, but its development has been suspended because I have been very busy lately, and I haven't found time to finish the new version yet. It's planned, however I can't say when it will be ready.

**Comment by JorgenSolli** [comment]
Thanks for getting back to me 😊 

Cool! Will there be a minor version of v2 supporting L10, or will I have to wait for v3?

Again; I appreciate your work on this ❤️

**Comment by alajusticia** [comment]
Thanks for your support :)
I'm not planning to support it in v2.

**Comment by alajusticia** [comment]
This package is now discontinued and replaced by a new one that supports Laravel 10 and 11: [Laravel Logins](https://github.com/alajusticia/laravel-logins)
